-- =============================================================================
-- BATCH INSERT SCRIPT: ApprovedCertifier Table (E39)
-- =============================================================================

BEGIN TRANSACTION;
GO

DECLARE @CertifierCount INT = 0;

CREATE TABLE #SourceData (
    CertifierCode NVARCHAR(10),
    CertifierName NVARCHAR(255)
);

INSERT INTO #SourceData (CertifierCode, CertifierName) VALUES
('H0001', 'ADELAIDE MOSQUE ISLAMIC SOCIETY OF SOUTH AUSTRALIA'),
('H0002', 'AL-IMAN ISLAMIC SOCIETY'),
('H0003', 'AUSTRALIAN FEDERATION OF ISLAMIC COUNCILS INC'),
('H0004', 'AUSTRALIAN HALAL AUTHORITY AND ADVISERS'),
('H0005', 'AUSTRALIAN HALAL FOOD SERVICES'),
('H0006', 'HALAL AUSTRALIA PTY LTD'),
('H0007', 'HALAL CERTIFICATION AUTHORITY-AUSTRALIA'),
('H0008', 'HALAL MEAT BOARD OF WESTERN AUSTRALIA'),
('H0010', 'HALAL SUPERVISORY BOARD OF SOUTH AUSTRALIA FOR THE KINGDOM OF SAUDI ARABIA'),
('H0011', 'ISLAMIC ASSOCIATION OF GERALDTON'),
('H0012', 'ISLAMIC ASSOCIATION OF KATANNING'),
('H0013', 'ISLAMIC COORDINATING COUNCIL OF VICTORIA'),
('H0014', 'ISLAMIC COUNCIL OF WESTERN AUSTRALIA'),
('H0015', 'PERTH MOSQUE INCORPORATED'),
('H0016', 'SUPREME ISLAMIC COUNCIL OF HALAL MEAT IN AUSTRALIA INC'),
('H0017', 'WESTERN AUSTRALIA HALAL AUTHORITY'),
('H0019', 'AUSTRALIAN HALAL DEVELOPMENT AND ACCREDITATION'),
('H0020', 'HALAL CERTIFICATION COUNCIL'),
('H0021', 'MUSLIM ASSOCIATION OF RIVERINA WAGGA WAGGA INC'),
('H0022', 'THE HALAL APPROVAL PTY LTD'),
('H0023', 'AUSTRALIAN NATIONAL IMAMS COUNCIL');

INSERT INTO [ApprovedCertifier] (CertifierCode, CertifierName)
SELECT s.CertifierCode, s.CertifierName
FROM #SourceData s
WHERE NOT EXISTS (
    SELECT 1 FROM [ApprovedCertifier] t 
    WHERE t.CertifierCode = s.CertifierCode
);

SET @CertifierCount = @@ROWCOUNT;
DROP TABLE #SourceData;

IF @CertifierCount > 0
    PRINT CAST(@CertifierCount AS NVARCHAR(10)) + ' records inserted successfully into Table ApprovedCertifier.';
ELSE
    PRINT 'No new records were inserted into Table ApprovedCertifier.';

COMMIT TRANSACTION;
GO