/* DEVOPS READY DATA MIGRATION: Table [PackageType] (E17)
   - Idempotent: Safe for multiple runs.
   - Integrity: Synchronizes PackageTypeCode and Description.
*/

SET NOCOUNT ON;
GO

PRINT 'Starting data ingestion for [PackageType] (E17)...';

BEGIN TRANSACTION;
BEGIN TRY
    IF OBJECT_ID('[dbo].[PackageType]', 'U') IS NOT NULL
    BEGIN
        -- Temporary table for high-performance staging
        CREATE TABLE #StagingPackageType (
            [Code] NVARCHAR(10),
            [Desc] NVARCHAR(200)
        );

        INSERT INTO #StagingPackageType ([Code], [Desc])
        VALUES 
        ('1A', 'DRUM, STEEL'), ('1B', 'DRUM, ALUMINIUM'), ('1D', 'DRUM, PLYWOOD'), ('1G', 'DRUM, FIBRE'),
        ('1W', 'DRUM, WOODEN'), ('2C', 'BARREL, WOODEN'), ('3A', 'JERRICAN, STEEL'), ('3H', 'JERRICAN, PLASTICS'),
        ('43', 'BAG, SUPER BULK'), ('44', 'BAG, POLYBAG'), ('4A', 'BOX, STEEL'), ('4B', 'BOX, ALUMINIUM'),
        ('4C', 'BOX, NATURAL WOOD'), ('4D', 'BOX, PLYWOOD'), ('4F', 'BOX, RECONSTITUTED WOOD'), ('4G', 'BOX, FIBREBOARD'),
        ('4H', 'BOX, PLASTICS'), ('5H', 'BAG, WOVEN PLASTIC'), ('5L', 'BAG, TEXTILE'), ('5M', 'BAG, PAPER'),
        ('6H', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE'), ('6P', 'COMPOSITE PACKAGING, GLASS RECEPTACLE'), ('AA', 'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC'), ('AB', 'RECEPTACLE, FIBRE'),
        ('AC', 'RECEPTACLE, PAPER'), ('AD', 'RECEPTACLE, WOODEN'), ('AE', 'AEROSOL'), ('AF', 'PALLET, MODULAR, COLLARS 80CMS * 60CMS'),
        ('AG', 'PALLET, SHRINKWRAPPED'), ('AH', 'PALLET, 100CMS * 110CMS'), ('AI', 'CLAMSHELL'), ('AJ', 'CONE'),
        ('AM', 'AMPOULE'), ('AP', 'AMPOULE, PROTECTED'), ('AT', 'ATOMIZER'), ('BA', 'BARREL'),
        ('BB', 'BOBBIN'), ('BC', 'BOTTLECRATE / BOTTLERACK'), ('BD', 'BOARD'), ('BE', 'BUNDLE'),
        ('BF', 'BALLOON, NON-PYROTECHNIC WITH STAND'), ('BG', 'BAG'), ('BH', 'BUNCH'), ('BI', 'BIN'),
        ('BJ', 'BUCKET'), ('BK', 'BASKET'), ('BL', 'BALE'), ('BM', 'BASIN'),
        ('BN', 'BALL'), ('BO', 'BOTTLE, NON-PROTECTED, CYLINDRICAL'), ('BP', 'BALLOON, PROTECTED'), ('BQ', 'BOTTLE, PROTECTED CYLINDRICAL'),
        ('BR', 'BAR'), ('BS', 'BOTTLE, NON-PROTECTED, BULBOUS'), ('BT', 'BOLT'), ('BU', 'BUTT'),
        ('BV', 'BOTTLE, PROTECTED BULBOUS'), ('BW', 'BOX, FOR LIQUIDS'), ('BX', 'BOX'), ('BY', 'BOARD, IN BUNDLE/BUNCH/TRUSS'),
        ('BZ', 'BARS, IN BUNDLE/BUNCH/TRUSS'), ('CA', 'CAN, RECTANGULAR'), ('CB', 'CRATE, BEER'), ('CC', 'CHURN'),
        ('CD', 'CAN, WITH HANDLE AND SPOUT'), ('CE', 'CREEL'), ('CF', 'COFFER'), ('CG', 'CAGE'),
        ('CH', 'CHEST'), ('CI', 'CANISTER'), ('CJ', 'COFFIN'), ('CK', 'CASK'),
        ('CL', 'COIL'), ('CM', 'CARD'), ('CN', 'CONTAINER, NOT OTHERWISE SPECIFIED AS TRANSPORT EQUIPMENT'), ('CO', 'CARBOY, NON-PROTECTED'),
        ('CP', 'CARBOY, PROTECTED'), ('CQ', 'CARTRIDGE'), ('CR', 'CRATE'), ('CS', 'CASE'),
        ('CT', 'CARTON'), ('CU', 'CUP'), ('CV', 'CASSETTE'), ('CW', 'CAGE, ROLL'),
        ('CX', 'CAN, CYLINDRICAL'), ('CY', 'CYLINDER'), ('CZ', 'CANVAS'), ('DA', 'CRATE, MULTIPLE LAYER, PLASTIC'),
        ('DB', 'CRATE, MULTIPLE LAYER, WOODEN'), ('DC', 'CRATE, MULTIPLE LAYER, CARDBOARD'), ('DG', 'CAGE, COMMONWEALTH HANDLING EQUIPMENT POOL (CHEP)'), ('DH', 'BOX, COMMONWEALTH HANDLING EQUIPMENT POOL (CHEP), EUROBOX'),
        ('DI', 'DRUM, IRON'), ('DJ', 'DEMIJOHN, NON-PROTECTED'), ('DK', 'DEMIJOHN, PROTECTED'), ('DL', 'DAIRY POT'),
        ('DM', 'DRUM'), ('DN', 'DISPENSER'), ('DP', 'DEMIJOHN'), ('DR', 'DRUM'),
        ('DS', 'TRAY, ONE LAYER NO COVER, PLASTIC'), ('DT', 'TRAY, ONE LAYER NO COVER, WOODEN'), ('DU', 'TRAY, ONE LAYER NO COVER, POLYSTYRENE'), ('DV', 'TRAY, ONE LAYER NO COVER, CARDBOARD'),
        ('DW', 'TRAY, TWO LAYER NO COVER, PLASTIC TRAY'), ('DX', 'TRAY, TWO LAYER NO COVER, WOODEN'), ('DY', 'TRAY, TWO LAYER NO COVER, CARDBOARD'), ('EC', 'BAG, PLASTIC'),
        ('ED', 'CASE, WITH PALLET BASE'), ('EE', 'CASE, WITH PALLET BASE, WOODEN'), ('EF', 'CASE, WITH PALLET BASE, CARDBOARD'), ('EG', 'CASE, WITH PALLET BASE, PLASTIC'),
        ('EH', 'CASE, WITH PALLET BASE, METAL'), ('EI', 'CASE, ISOTHERMIC'), ('EN', 'ENVELOPE'), ('FC', 'FRUIT CRATE'),
        ('FD', 'FRAMED CRATE'), ('FI', 'FIRKIN'), ('FL', 'FLASK'), ('FO', 'FOOTLOCKER'),
        ('FP', 'FILMPACK'), ('FR', 'FRAME'), ('FT', 'FOODTAINER'), ('FW', 'CARTON, RIGID'),
        ('FX', 'BAG, FLEXIBLE CONTAINER'), ('GB', 'GOTTLE, GAS'), ('GI', 'GIRDER'), ('GZ', 'GIRDERS, IN BUNDLE/BUNCH/TRUSS'),
        ('HA', 'BASKET, WITH HANDLE, PLASTIC'), ('HB', 'BASKET, WITH HANDLE, WOODEN'), ('HC', 'BASKET, WITH HANDLE, CARDBOARD'), ('HG', 'HOGSHEAD'),
        ('HN', 'HANGER'), ('HR', 'HAMPER'), ('IA', 'PACKAGE, DISPLAY, WOODEN'), ('IB', 'PACKAGE, DISPLAY, CARDBOARD'),
        ('IC', 'PACKAGE, DISPLAY, PLASTIC'), ('ID', 'PACKAGE, DISPLAY, METAL'), ('IE', 'PACKAGE, SHOW'), ('IF', 'PACKAGE, FLOW'),
        ('IG', 'PACKAGE, PAPER WRAPPED'), ('IK', 'PACKAGE, CARDBOARD, WITH BOTTLE GRIP-HOLES'), ('IN', 'INGOT'), ('IZ', 'INGOTS, IN BUNDLE/BUNCH/TRUSS'),
        ('JB', 'BAG, JUMBO'), ('JC', 'JERRICAN, RECTANGULAR'), ('JG', 'JUG'), ('JR', 'JAR'),
        ('JT', 'JUTEBAG'), ('JY', 'JERRICAN, CYLINDRICAL'), ('KG', 'KEG'), ('KI', 'KIT'),
        ('LE', 'LUGGAGE'), ('LG', 'LOG'), ('LT', 'LOT'), ('LV', 'LIFTVAN'),
        ('LZ', 'LOGS, IN BUNDLE/BUNCH/TRUSS'), ('MB', 'BAG, MULTIPLY'), ('MC', 'CRATE, MILK'), ('MS', 'SACK, MULTI-WALL'),
        ('MT', 'MAT'), ('MW', 'RECEPTACLE, PLASTIC WRAPPED'), ('MX', 'MATCHBOX'), ('NA', 'NOT AVAILABLE'),
        ('NE', 'UNPACKED OR UNPACKAGED'), ('NF', 'UNPACKED OR UNPACKAGED, SINGLE UNIT'), ('NG', 'UNPACKED OR UNPACKAGED, MULTIPLE UNITS'), ('NS', 'NEST'),
        ('NT', 'NET'), ('NU', 'NET, TUBE, PLASTIC'), ('NV', 'NET, TUBE, TEXTILE'), ('OA', 'PALLET, CHEP 40CM * 60CM'),
        ('OB', 'PALLET, CHEP 80CM * 120CM'), ('OC', 'PALLET, CHEP 100CM * 120CM'), ('OD', 'PALLET, ASSET 80CM * 120CM'), ('OE', 'PALLET, ASSET 100CM * 120CM'),
        ('OF', 'PLATFORM, UNSPECIFIED WEIGHT OR DIMENSION'), ('OK', 'OCTABIN'), ('OT', 'OCTABIN'), ('OU', 'NON-STANDARD PACKAGING'),
        ('P2', 'PAN'), ('PA', 'PACKET'), ('PB', 'PALLET, BOX'), ('PC', 'PARCEL'),
        ('PD', 'PALLET, ASSET'), ('PE', 'PALLET, ASSET'), ('PF', 'PEN'), ('PG', 'PLATE'),
        ('PH', 'PITCHER'), ('PI', 'PIPE'), ('PJ', 'PAIL'), ('PK', 'PACKAGE'),
        ('PL', 'PAIL'), ('PN', 'PLANK'), ('PO', 'POUCH'), ('PP', 'PIECE'),
        ('PR', 'RECEPTACLE, PLASTIC'), ('PT', 'POT'), ('PU', 'TRAY'), ('PV', 'PIPES, IN BUNDLE/BUNCH/TRUSS'),
        ('PX', 'PALLET'), ('PY', 'PLATES, IN BUNDLE/BUNCH/TRUSS'), ('PZ', 'PLANKS, IN BUNDLE/BUNCH/TRUSS'), ('QA', 'DRUM, STEEL, NON-REMOVABLE HEAD'),
        ('QB', 'DRUM, STEEL, REMOVABLE HEAD'), ('QC', 'DRUM, ALUMINIUM, NON-REMOVABLE HEAD'), ('QD', 'DRUM, ALUMINIUM, REMOVABLE HEAD'), ('QF', 'DRUM, PLASTIC, NON-REMOVABLE HEAD'),
        ('QG', 'DRUM, PLASTIC, REMOVABLE HEAD'), ('QH', 'BARREL, WOODEN, BUNG TYPE'), ('QJ', 'BARREL, WOODEN, REMOVABLE HEAD'), ('QK', 'JERRICAN, STEEL, NON-REMOVABLE HEAD'),
        ('QL', 'JERRICAN, STEEL, REMOVABLE HEAD'), ('QM', 'JERRICAN, PLASTIC, NON-REMOVABLE HEAD'), ('QN', 'JERRICAN, PLASTIC, REMOVABLE HEAD'), ('QP', 'BOX, WOODEN, NATURAL WOOD, ORDINARY'),
        ('QQ', 'BOX, WOODEN, NATURAL WOOD, SIFT PROOF'), ('QR', 'BOX, PLASTIC, EXPANDED'), ('QS', 'BOX, PLASTIC, SOLID'), ('RD', 'ROD'),
        ('RG', 'RING'), ('RJ', 'RACK, CLOTHING HANGER'), ('RK', 'RACK'), ('RL', 'REEL'),
        ('RO', 'ROLL'), ('RT', 'REDNET'), ('RZ', 'RODS, IN BUNDLE/BUNCH/TRUSS'), ('SA', 'SACK'),
        ('SB', 'SLAB'), ('SC', 'SHALLOW CRATE'), ('SD', 'SPINDLE'), ('SE', 'SEA-CHEST'),
        ('SH', 'SACHET'), ('SI', 'SKID'), ('SK', 'SKELETON CASE'), ('SL', 'SLIPSHEET'),
        ('SM', 'SHEETMETAL'), ('SO', 'SPOOL'), ('SP', 'SHEET, PLASTIC WRAPPED'), ('SS', 'CASE, STEEL'),
        ('ST', 'SHEET'), ('SU', 'SUITCASE'), ('SV', 'ENVELOPE, STEEL'), ('SW', 'SHRINKWRAPPED'),
        ('SY', 'SLEEVE'), ('SZ', 'SHEETS, IN BUNDLE/BUNCH/TRUSS'), ('T1', 'TABLET'), ('TB', 'TUB'),
        ('TC', 'TEA-CHEST'), ('TD', 'TUBE, COLLAPSIBLE'), ('TI', 'TIERCE'), ('TK', 'TANK, RECTANGULAR'),
        ('TL', 'TUBE, WITH NOZZLE'), ('TN', 'TIN'), ('TO', 'TUN'), ('TR', 'TRUNK'),
        ('TS', 'TRUSS'), ('TU', 'TUBE'), ('TV', 'TUBE, WITH NOZZLE'), ('TY', 'TANK, CYLINDRICAL'),
        ('TZ', 'TUBES, IN BUNDLE/BUNCH/TRUSS'), ('UC', 'UNCAGED'), ('UN', 'UNIT'), ('VA', 'VAT'),
        ('VG', 'BULK, GAS (AT 1031 MBAR AND 15 DEGREES C)'), ('VI', 'VIAL'), ('VK', 'VANPACK'), ('VL', 'BULK, LIQUID'),
        ('VO', 'BULK, SOLID, LARGE PARTICLES (NODULES)'), ('VP', 'VACUUM-PACKED'), ('VQ', 'BULK, LIQUID, GAS'), ('VR', 'BULK, SOLID, GRANULAR PARTICLES (GRAINS)'),
        ('VY', 'BULK, SOLID, FINE PARTICLES (POWDERS)'), ('WA', 'INTERMEDIATE BULK CONTAINER'), ('WB', 'WICKERBOTTLE'), ('WC', 'INTERMEDIATE BULK CONTAINER, STEEL'),
        ('WD', 'INTERMEDIATE BULK CONTAINER, ALUMINIUM'), ('WF', 'INTERMEDIATE BULK CONTAINER, METAL'), ('WG', 'INTERMEDIATE BULK CONTAINER, RECEPTACLE, PLASTIC'), ('WH', 'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, WITH STRUCTURAL EQUIPMENT, SOLIDS'),
        ('WI', 'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, FREESTANDING, SOLIDS'), ('WJ', 'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, WITH STRUCTURAL EQUIPMENT, LIQUIDS'), ('WK', 'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, FREESTANDING, LIQUIDS'), ('WL', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, PLASTIC RECEPTACLE, SOLIDS'),
        ('WM', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, PLASTIC RECEPTACLE, PRESSURISED, SOLIDS'), ('WN', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, PLASTIC RECEPTACLE, LIQUIDS'), ('WO', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, PLASTIC RECEPTACLE, PRESSURISED, LIQUIDS'), ('WP', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, OTHER RECEPTACLE'),
        ('WQ', 'INTERMEDIATE BULK CONTAINER, FIBREBOARD'), ('WR', 'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, WITHOUT COATING/LINER'), ('WS', 'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, COATED'), ('WT', 'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, WITH LINER'),
        ('WU', 'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, COATED AND WITH LINER'), ('WV', 'INTERMEDIATE BULK CONTAINER, TEXTILE, WITHOUT COATING/LINER'), ('WW', 'INTERMEDIATE BULK CONTAINER, TEXTILE, COATED'), ('WX', 'INTERMEDIATE BULK CONTAINER, TEXTILE, WITH LINER'),
        ('WY', 'INTERMEDIATE BULK CONTAINER, TEXTILE, COATED AND WITH LINER'), ('WZ', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL'), ('XA', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT'), ('XB', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'),
        ('XC', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('XD', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('XF', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('XG', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'),
        ('XH', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('XJ', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('XK', 'INTERMEDIATE BULK CONTAINER, COMPOSITE, RECEPTACLE, PLASTIC'), ('YA', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN STEEL DRUM'),
        ('YB', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN STEEL CRATE BOX'), ('YC', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN ALUMINIUM DRUM'), ('YD', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN ALUMINIUM CRATE'), ('YF', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN WOODEN BOX'),
        ('YG', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLYWOOD DRUM'), ('YH', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLYWOOD BOX'), ('YJ', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN FIBRE DRUM'), ('YK', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN FIBREBOARD BOX'),
        ('YL', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLASTIC DRUM'), ('YM', 'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN SOLID PLASTIC BOX'), ('YN', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN STEEL DRUM'), ('YP', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN STEEL CRATE BOX'),
        ('YQ', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN ALUMINIUM DRUM'), ('YR', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN ALUMINIUM CRATE'), ('YS', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN WOODEN BOX'), ('YT', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN PLYWOOD DRUM'),
        ('YU', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN WICKER HAMPER'), ('YV', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN FIBRE DRUM'), ('YW', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN FIBREBOARD BOX'), ('YX', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN EXPANDED PLASTIC PACK'),
        ('YY', 'COMPOSITE PACKAGING, GLASS RECEPTACLE IN SOLID PLASTIC PACK'), ('YZ', 'INTERMEDIATE BULK CONTAINER, WOODEN, NATURAL WOOD, WITH INNER LINER'), ('ZA', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL'), ('ZB', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT'),
        ('ZC', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT'), ('ZD', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT'), ('ZF', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT'), ('ZG', 'INTERMEDIATE BULK CONTAINER, PAPER, MULTIWALL, WATER RESISTANT');

        -- Final Ingestion using MERGE for idempotency
        MERGE INTO [dbo].[PackageType] AS target
        USING #StagingPackageType AS src
        ON (target.[PackageTypeCode] = src.[Code])
        WHEN MATCHED THEN
            UPDATE SET target.[PackageTypeDescription] = src.[Desc]
        WHEN NOT MATCHED THEN
            INSERT ([PackageTypeCode], [PackageTypeDescription])
            VALUES (src.[Code], src.[Desc]);

        DECLARE @Count INT = @@ROWCOUNT;
        PRINT 'SUCCESS: ' + CAST(@Count AS VARCHAR(10)) + ' records synchronized into [PackageType].';
        
        DROP TABLE #StagingPackageType;
    END
    ELSE
    BEGIN
        PRINT 'ERROR: Table [dbo].[PackageType] does not exist.';
    END

    COMMIT TRANSACTION;
    PRINT 'Data migration for [PackageType] completed successfully.';

END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    PRINT 'CRITICAL ERROR: ' + ERROR_MESSAGE();
    THROW;
END CATCH;
GO